Separate domain store
mycel-domain/mycel pull request #71
Opened 2023-08-23 08:30 UTC by yujiym

PR for https://github.com/mycel-domain/mycel/issues/69

> 1. Scaffold TopLevelDomain store with `ignite s map topLevelDomain expirationDate:uint --index name --no-message`
> 2. at `proto/mycel/registry'
>   - Define TopLevelDomain store
>   - Rename Domain -> SecondLevelDomain store
>   - Define SecondLevelDomain store
>   - `genesis.proto`: rename Domain->SecondLevelDomain
> 3. Generate type from proto with `ignite g proto-go`
> 4. Fix compilation errors and  update logic and tests at `x/registry/types`
>    - `domain.go` -> `second_level_domain.go`
>    - `domain_test.go` -> `second_level_domain_test.go`
>    - `validate_domain.go` -> `validate_second_level_domain.go`
>    - `genesis.go`: register .cel TLD
> 5. Fix compilation errors and  update logic and tests at `x/registry/keeper`
>    - `register_domain.go`: update registration logic
>    - `validate_registration.go`: update validation logic
>    - `update_{wallet|dns}_record.go`
> 6. Update tx/query 
>    - `proto/mycel/registry/query.proto`: domain -> second-level-domain
>    - `x/registry/client/cli/` fix compilation errors

2023-08-24 11:09 UTC, yujiym commented on proto/mycel/registry/top_level_domain.proto
> +  int64 expirationDate = 2;
change 'uint'

2023-08-24 11:38 UTC, taryune commented on x/registry/keeper/domain.go
rename to second_level_domain.go

2023-08-24 11:38 UTC, taryune commented on x/registry/keeper/msg_server_register_domain.go
rename msg_server_resgister_second_level_domain.go

2023-08-24 11:38 UTC, taryune commented on x/registry/keeper/msg_server_register_domain_test.go
rename msg_server_resgister_second_level_domain_test.go

2023-08-24 11:38 UTC, taryune commented on x/registry/keeper/register_domain.go
rename to register_second_level_domain.go

2023-08-28 09:35 UTC, taryune requested changes

2023-08-28 09:35 UTC, taryune commented on x/registry/keeper/msg_server_register_second_level_domain_test.go
can you add the case: invalid parent

2023-08-28 09:35 UTC, taryune commented on x/registry/keeper/msg_server_register_second_level_domain_test.go
check if parent's `subdomainCount` is increased

2023-08-28 10:29 UTC, yujiym commented on x/registry/keeper/msg_server_register_second_level_domain_test.go
https://github.com/mycel-domain/mycel/blob/f707acd85cbf1e3df378c3613245de86a1f97b97/x/registry/keeper/msg_server_register_second_level_domain_test.go#L107-L108

2023-08-30 05:01 UTC, yujiym commented on x/registry/keeper/msg_server_register_second_level_domain_test.go
Added a case of no parent TLD.
I commented out for parent check (because can't run the test setup in this case). This should be tested in other tests.

2023-08-30 07:13 UTC, taryune approved these changes
<img src="https://media3.giphy.com/media/l3vR1tvIhCrrZsty0/giphy.gif"/>

2023-08-31 11:39 UTC, merged